name: Delivery

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
  workflow_dispatch:
  workflow_call:

jobs:
  build:
    name: Build & Push Image
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Log in to GHCR
        run: echo "${{ secrets.CR_PAT }}" | docker login ghcr.io -u "${{ secrets.DOCKER_GITHUB_USERNAME }}" --password-stdin

      - name: Build and push image
        run: |
          docker build -t ghcr.io/devops-team36/whoknows:latest -f server_go/deploy/Dockerfile server_go
          docker push ghcr.io/devops-team36/whoknows:latest
