name: Lint code base

on:
  push:
    branches: [dev]
  pull_request:
    branches: [dev]

jobs:
  build:
    name: Lint code base
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Lint code base
        uses: super-linter/super-linter@v7
        env:
          VALIDATE_ALL_CODEBASE: false
          DEFAULT_BRANCH: dev
          VALIDATE_GO: false
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}